# Generated by Django 5.0.6 on 2026-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image_url', models.CharField(max_length=500)),
                ('image_path', models.CharField(max_length=500)),
                ('prompt_used', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generated Image Cache',
                'verbose_name_plural': 'Generated Image Cache',
                'db_table': 'generated_image_cache',
            },
        ),
    ]
