# Generated by Django 5.0.6 on 2026-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_city_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
