# Generated by Django 5.0.6 on 2026-05-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_city_options_city_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedrecipe',
            options={},
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='accounts.recipe'),
        ),
    ]
