# Generated by Django 5.0.6 on 2026-05-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_savedrecipe_options_alter_savedrecipe_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedrecipe',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='accounts.recipe'),
        ),
    ]
