# Generated by Django 5.0.6 on 2026-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_savedrecipe_options_alter_savedrecipe_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedrecipe',
            options={},
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
