# Generated by Django 5.0.6 on 2026-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_savedrecipe_options_recipe_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
