# Generated by Django 5.0.6 on 2026-05-11 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_recipe_video_url_recipe_youtube_video_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('lite', 'Lite & Healthy'), ('spicy', 'Spicy & Flavorful'), ('balanced', 'Balanced'), ('without_preference', 'Without Health Preference')], max_length=20)),
                ('weekly_plan', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Meal Plan',
                'verbose_name_plural': 'Saved Meal Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
