# Generated by Django 5.0.6 on 2026-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_savedmealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmealplan',
            name='dietary_preference',
            field=models.CharField(default='veg', max_length=20),
        ),
    ]
