# Generated by Django 5.0.6 on 2026-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_savedmealplan_dietary_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmealplan',
            name='health_condition',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('blood_pressure', 'Blood Pressure'), ('heart_condition', 'Heart Condition'), ('balanced', 'Balanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='savedmealplan',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('lite', 'Lite & Healthy'), ('spicy', 'Spicy & Flavorful'), ('balanced', 'Balanced'), ('without_preference', 'Without Health Preference')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='savedmealplan',
            name='dietary_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
