# Generated by Django 5.0.6 on 2026-05-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_savedmealplan_health_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedmealplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='kcal',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='substitutions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='youtube_video_id',
        ),
        migrations.RemoveField(
            model_name='savedmealplan',
            name='diet_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_low_fat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_sugar_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='No ingredients listed'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions provided'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='savedmealplan',
            name='dietary_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedmealplan',
            name='health_condition',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('blood_pressure', 'Blood Pressure'), ('heart_condition', 'Heart Condition'), ('balanced', 'Balanced')], default='balanced', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedmealplan',
            name='weekly_plan',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recipe'),
        ),
    ]
