# Generated by Django 5.0.6 on 2026-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_savedmealplan_options_remove_recipe_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='Pakistani', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='spice_level',
            field=models.CharField(choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot')], default='Medium', max_length=20),
        ),
    ]
