# Generated by Django 5.0.6 on 2026-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_recipe_cuisine_recipe_dietary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ai_generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_generated/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_generation_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
