# Generated by Django 5.0.6 on 2026-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_recipe_created_at_remove_recipe_creator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('prep_time', models.IntegerField(default=30)),
                ('kcal', models.IntegerField(default=350)),
                ('cuisine', models.CharField(default='Pakistani', max_length=100)),
                ('dietary_type', models.CharField(blank=True, default='mixed', max_length=50)),
                ('spice_level', models.CharField(blank=True, default='Medium', max_length=20)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='accounts_ai_title_b61a61_idx'), models.Index(fields=['-view_count'], name='accounts_ai_view_co_9732dc_idx')],
            },
        ),
    ]
