# Generated by Django 5.0.6 on 2026-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_recipe_ai_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='estimated_protein',
            field=models.IntegerField(default=0, help_text='Protein in grams'),
        ),
    ]
