# Generated by Django 5.0.6 on 2026-05-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_recipe_estimated_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ai_generated_image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_generation_attempted',
        ),
    ]
