# Generated by Django 5.0.6 on 2026-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aigeneratedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedrecipe',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='Pakistani', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='season',
            field=models.CharField(blank=True, default='Summer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_bookmarks',
            field=models.JSONField(default=list),
        ),
    ]
