# Generated by Django 5.0.6 on 2026-05-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_aigeneratedrecipe_season_recipe_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedrecipe',
            name='season',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='season',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_bookmarks',
        ),
    ]
