# Generated by Django 5.0.6 on 2026-05-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_recipe_ai_generated_image_and_more'),
        ('accounts', '0020_usersearchhistory_userviewedrecipe'),
    ]

    operations = [
    ]
