# Generated by Django 5.0.6 on 2026-06-05 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recipes_viewed', models.IntegerField(default=0)),
                ('total_recipes_saved', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='ViewedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=100)),
                ('recipe_title', models.CharField(max_length=255)),
                ('recipe_data', models.JSONField(default=dict)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_viewed_history',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'recipe_id')},
            },
        ),
    ]
