# Generated by Django 5.0.6 on 2026-06-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_pandamart_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='city_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AIGeneratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('prep_time', models.IntegerField(default=30)),
                ('kcal', models.IntegerField(default=350)),
                ('cuisine', models.CharField(default='Pakistani', max_length=100)),
                ('dietary_type', models.CharField(blank=True, default='mixed', max_length=50)),
                ('spice_level', models.CharField(blank=True, default='Medium', max_length=20)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='recipes_aig_title_6735d7_idx'), models.Index(fields=['-view_count'], name='recipes_aig_view_co_2b4125_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='No description provided')),
                ('ingredients', models.TextField(default='No ingredients listed')),
                ('instructions', models.TextField(default='No instructions provided')),
                ('prep_time', models.IntegerField(default=0, help_text='Time in minutes')),
                ('calories', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/')),
                ('cuisine', models.CharField(default='Pakistani', max_length=100)),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('spice_level', models.CharField(choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Hot', 'Hot')], default='Medium', max_length=20)),
                ('estimated_protein', models.IntegerField(default=0, help_text='Protein in grams')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_sugar_free', models.BooleanField(default=False)),
                ('is_low_fat', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.city')),
            ],
        ),
    ]
