# Generated by Django 5.0.6 on 2026-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='famous_dishes',
            field=models.JSONField(default=list),
        ),
    ]
