# Generated by Django 5.0.6 on 2026-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_city_famous_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='famous_dishes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
