/*
# Seed Cities and Recipes Data

Populates recipes_city (10 cities) and recipes_recipe (32 recipes) with
Pakistani recipe data from the Ingrido seed JSON files.
*/

-- CITIES
INSERT INTO recipes_city (name, region, tagline, latitude, longitude, is_pandamart_available, image, famous_dishes)
VALUES
('Lahore','Punjab','The Cultural Heart of Pakistan - Food Capital',31.5497,74.3436,true,'/city_images/lahore.jpeg','["Chargha","Gol Gappay","Butt Karahi","Falooda","Fried Fish"]'::jsonb),
('Karachi','Sindh','City of Lights - Where Flavors Never Sleep',24.8607,67.0011,true,'/city_images/karachi.jpeg','["Karachi Biryani","Bun Kebab","Haleem","Burns Road Qeema","Kulfi Falooda"]'::jsonb),
('Islamabad','Capital Territory','The Beautiful Capital - Modern Cuisine Hub',33.6844,73.0479,true,'/city_images/islamabad.jpeg','["Chicken Tikka","Shawarma","Trout Fish"]'::jsonb),
('Peshawar','Khyber Pakhtunkhwa','City of Flowers - Land of Traditional BBQ',34.0151,71.5249,false,'/city_images/peshawar.jpeg','["Chapli Kebab","Namak Mandi Karahi","Mutton Korma","Lamb Sajji"]'::jsonb),
('Multan','Punjab','City of Saints - Sweet Delights Paradise',30.1575,71.5249,false,'/city_images/multan.jpeg','["Multani Sohan Halwa","Mango Kulfi","Channa Chaat","Pati Gali Biryani","Sajji"]'::jsonb),
('Quetta','Balochistan','Fruit Garden of Pakistan - Balochi Cuisine',30.1798,66.9750,false,'/city_images/quetta.jpeg','["Sajji","Landhi"]'::jsonb),
('Faisalabad','Punjab','Manchester of Pakistan - Street Food Hub',31.4504,73.1350,true,'/city_images/faisalabad.jpeg','["Channay"]'::jsonb),
('Rawalpindi','Punjab','Military City - Traditional Flavors',33.5651,73.0169,true,'/city_images/rawalpindi.jpeg','["Murgh Cholay","Chapli Kebab","Channay"]'::jsonb),
('Sialkot','Punjab','City of Sports Goods - Hidden Food Gems',32.4945,74.5229,false,'/city_images/sialkot.jpeg','["Kulfi Falooda","Gola Ganda Kala Khatta","Chicken Pulao","Samosa Chaat"]'::jsonb),
('Hyderabad','Sindh','City of Winds - Authentic Sindhi Cuisine',25.3960,68.3578,false,'/city_images/hyderabad.jpeg','["Bhugga","Sindhi Kadi Chawal","Pappu Masala","Double Roti"]'::jsonb)
ON CONFLICT (name) DO NOTHING;

-- RECIPES (using a DO block to map city_name -> city_id)
DO $$
DECLARE
  c_lahore bigint := (SELECT id FROM recipes_city WHERE name='Lahore');
  c_karachi bigint := (SELECT id FROM recipes_city WHERE name='Karachi');
  c_islamabad bigint := (SELECT id FROM recipes_city WHERE name='Islamabad');
  c_peshawar bigint := (SELECT id FROM recipes_city WHERE name='Peshawar');
  c_multan bigint := (SELECT id FROM recipes_city WHERE name='Multan');
  c_quetta bigint := (SELECT id FROM recipes_city WHERE name='Quetta');
  c_faisalabad bigint := (SELECT id FROM recipes_city WHERE name='Faisalabad');
  c_rawalpindi bigint := (SELECT id FROM recipes_city WHERE name='Rawalpindi');
  c_sialkot bigint := (SELECT id FROM recipes_city WHERE name='Sialkot');
  c_hyderabad bigint := (SELECT id FROM recipes_city WHERE name='Hyderabad');
BEGIN
  -- Lahore
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Chargha','A legendary Lahori dish of whole roasted chicken marinated in traditional spices and deep-fried to golden perfection.','1 whole chicken (1.5 kg), 1 cup yogurt, 2 tbsp ginger-garlic paste, 2 tbsp red chili powder, 1 tbsp turmeric, 2 tbsp garam masala, 1 tbsp cumin, 1 tbsp coriander, 1 tbsp chaat masala, 2 tbsp lemon juice, Salt, 4 tbsp mustard oil, Oil for frying','Clean chicken and make deep cuts. Mix all marinade ingredients and apply generously. Refrigerate for 6 hours. Heat oil and deep fry chicken for 15-20 minutes until golden and crispy. Reduce heat and cook for another 10-15 minutes. Garnish with coriander, lemon wedges, and onion rings. Serve hot with naan.',60,850,'chargha.jpg','Pakistani','non_veg','Hot',55,c_lahore,false,true,false),
  ('Gol Gappay','Crispy hollow puris filled with spicy tangy water, chickpeas, and potatoes - Lahore''s ultimate street food.','For Puris: 1 cup semolina, 2 tbsp flour, 1/2 tsp baking soda, Salt, Oil. For Pani: Mint, coriander, green chilies, ginger, tamarind, chaat masala, black salt, cumin, water. For Filling: Chickpeas, potatoes, sprouts, onion, spices.','Make stiff dough with semolina and flour. Roll thin and cut into circles. Deep fry until puffed and golden. Blend all pani ingredients and strain. Mix filling ingredients. Make hole in puri, fill with mixture, dip in pani, top with sev. Eat immediately.',45,280,'gol_gappay.jpg','Pakistani','veg','Hot',8,c_lahore,true,true,false),
  ('Butt Karahi','Lahore''s famous chicken karahi cooked in a rich tomato-based gravy with ginger, garlic, and green chilies.','1 kg chicken, 1/2 cup ghee, 2 tbsp ginger paste, 2 tbsp garlic paste, 6 tomatoes pureed, 8 green chilies, 2 tbsp red chili powder, 1 tbsp coriander powder, 1 tbsp garam masala, 1 cup fresh coriander, Salt','Heat ghee in karahi. Add ginger-garlic paste and chicken. Cook until chicken changes color. Add tomato puree and spices. Cook on high heat until oil separates. Add green chilies and cook for 5 minutes. Sprinkle garam masala. Garnish with coriander and ginger. Serve with naan.',40,720,'butt_karahi.jpg','Pakistani','non_veg','Hot',48,c_lahore,false,true,false),
  ('Falooda','Beloved dessert drink combining rose syrup, vermicelli noodles, basil seeds, milk, and ice cream topped with nuts.','1 liter milk, 1/2 cup falooda sev, 3 tbsp basil seeds, 1/2 cup rose syrup, 1/4 cup sugar, 2 scoops vanilla ice cream, Almonds, pistachios, cashews','Soak basil seeds in water for 15 minutes. Cook falooda sev, drain and chill. In a glass, add rose syrup, basil seeds, and falooda noodles. Pour chilled milk. Add ice cream. Drizzle more rose syrup. Garnish with nuts. Serve immediately.',20,380,'falooda.jpg','Pakistani','veg','Mild',8,c_lahore,true,false,false),
  ('Fried Fish','Spicy tangy fried fish marinated in traditional spices and gram flour, deep-fried until golden and crispy.','1 kg fish fillets, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 1 tbsp cumin, 1 tbsp coriander, 1 tbsp chaat masala, 3 tbsp lemon juice, 1/2 cup gram flour, 2 tbsp rice flour, Oil for frying','Marinate fish with all spices and lemon juice for 30 minutes. Add gram flour and rice flour. Coat well. Deep fry on medium heat until golden and crispy. Serve with mint chutney, onion rings, and lemon wedges.',45,480,'fish.jpg','Pakistani','non_veg','Medium',38,c_lahore,false,true,false)
  ON CONFLICT DO NOTHING;

  -- Karachi
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Karachi Biryani','Fragrant spicy rice dish with chicken, potatoes, and Karachi''s special spice blend.','1 kg chicken, 4 cups basmati rice, 1 cup yogurt, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 2 tbsp biryani masala, 1/2 cup fried onions, 2 tomatoes, 2 potatoes, 1/2 cup oil','Marinate chicken with yogurt and spices for 2 hours. Cook rice until 70% done. Cook chicken with tomatoes and potatoes until tender. Layer rice over chicken. Sprinkle fried onions, mint, coriander, ghee, and kewra. Cover and cook on low for 20-25 minutes. Serve with raita.',90,650,'karachi_biryani.jpg','Pakistani','non_veg','Hot',35,c_karachi,false,true,false),
  ('Bun Kebab','Karachi''s famous burger with spicy potato patty, mint chutney, and fresh vegetables.','4 potatoes, 1/2 cup peas, ginger-garlic paste, red chili powder, chaat masala, cumin, cornflour, Mint chutney, Burger buns, Onion, Tomato','Boil and mash potatoes. Mix with peas, spices, and cornflour. Shape into patties and shallow fry until golden. Blend chutney ingredients. Toast buns with butter. Spread chutney, place patty, add onions and tomatoes. Serve hot.',30,420,'bun_kebab.jpg','Pakistani','veg','Medium',12,c_karachi,true,false,false),
  ('Haleem','Slow-cooked stew of meat, lentils, and wheat cooked for hours until creamy.','500g beef, 1 cup mixed lentils, 1/2 cup wheat, 1 cup yogurt, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 1 tbsp garam masala, 1/2 cup oil, Fried onions','Soak lentils and wheat overnight. Pressure cook with meat until tender. Blend until smooth. Heat oil, add ginger-garlic. Add blended mixture and cook on low heat for 2-3 hours. Add yogurt and spices. Cook until oil separates. Garnish with fried onions.',240,580,'karachi_haleem.jpg','Pakistani','non_veg','Medium',40,c_karachi,false,true,false),
  ('Burns Road Qeema','Spicy minced meat dish cooked with peas, tomatoes, and special spice blend.','500g beef mince, 1/2 cup oil, 2 onions, 2 tbsp ginger-garlic, 3 tomatoes pureed, 1/2 cup peas, 2 tbsp red chili powder, 1 tbsp garam masala','Heat oil and fry onions until golden. Add ginger-garlic and mince. Cook until mince changes color. Add tomato puree and spices. Cook until oil separates. Add peas and cook for 5 minutes. Add garam masala. Garnish with coriander. Serve with pav or naan.',40,520,'burns_road_qeema.jpg','Pakistani','non_veg','Hot',32,c_karachi,false,true,false),
  ('Kulfi Falooda','Rich creamy frozen dessert with falooda noodles, rose syrup, and nuts.','1 liter milk, 1/2 cup khoya, 1/2 cup sugar, 1/4 cup milk powder, 1 tbsp cornflour, 1 tsp cardamom, 1/2 cup falooda sev, 2 tbsp basil seeds, 1/2 cup rose syrup','Boil milk and reduce to half. Add khoya, milk powder, and cornflour. Cook until thickened. Add sugar and cardamom. Freeze in molds. Cook falooda sev and soak basil seeds. Layer rose syrup, basil seeds, falooda, and kulfi. Garnish with nuts.',480,450,'kulfi_falooda.jpg','Pakistani','veg','Mild',10,c_karachi,true,false,false)
  ON CONFLICT DO NOTHING;

  -- Islamabad
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Chicken Tikka','Famous grilled chicken tikka from Monal Restaurant marinated in cream and spices.','1 kg chicken thighs, 1 cup yogurt, 1/2 cup cream, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 1 tbsp garam masala, 2 tbsp lemon juice, 1 tbsp chaat masala','Mix all marinade ingredients. Marinate chicken for 4-6 hours. Skewer and cook in tandoor or grill until charred. Sprinkle chaat masala. Serve with mint chutney and naan.',50,520,'tikka.jpg','Pakistani','non_veg','Medium',48,c_islamabad,false,true,false),
  ('Shawarma','Islamabad''s famous shawarma with tangy garlic sauce and perfectly roasted meat.','1 kg chicken, 1/2 cup yogurt, 1/4 cup vinegar, 2 tbsp shawarma spice, 4 tbsp garlic paste. For Garlic Sauce: 1 cup mayo, 2 tbsp garlic paste, 1 tbsp lemon juice, 1/4 cup yogurt','Marinate meat overnight. Stack on vertical spit and roast slowly. Shave off thin slices as outer layer cooks. Mix garlic sauce ingredients. Serve wrapped in bread with garlic sauce, pickles, fries, and hot sauce.',720,550,'shawarma.jpg','Middle Eastern','non_veg','Medium',28,c_islamabad,false,false,false),
  ('Trout Fish','Freshwater trout from Margalla Hills streams, grilled with herbs and lemon.','4 whole trout fish, 2 tbsp garlic paste, 2 tbsp lemon juice, 1 tbsp black pepper, 2 tbsp fresh dill, 2 tbsp parsley, 4 tbsp butter','Clean trout and make slits. Mix garlic paste, lemon juice, pepper, herbs, butter, and salt. Rub marinade all over fish. Wrap in foil with butter. Grill for 15-20 minutes, turning once. Serve hot with lemon wedges.',30,380,'trout_fish.jpg','Pakistani','non_veg','Mild',42,c_islamabad,false,true,true)
  ON CONFLICT DO NOTHING;

  -- Peshawar
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Chapli Kebab','Thin crispy beef patty with pomegranate seeds - Peshawar style.','1 kg beef mince, 2 onions, 2 tomatoes, 1 cup coriander, 1/2 cup pomegranate seeds, 4 green chilies, 2 eggs, 1/2 cup cornflour, 2 tbsp red chili flakes','Mix all ingredients and rest for 30 minutes. Form into thin flat patties. Shallow fry on high heat for 3-4 minutes each side until very crispy. Serve with mint chutney, onion rings, and naan.',40,540,'peshawari_chapli.jpg','Pakistani','non_veg','Hot',30,c_peshawar,false,true,false),
  ('Namak Mandi Karahi','Simple yet flavorful karahi from Peshawar''s famous Namak Mandi using minimal spices and pure desi ghee.','1 kg mutton, 1 cup desi ghee, 4 tomatoes, 2 tbsp ginger paste, 2 tbsp garlic paste, 2 tbsp black pepper, 8 green chilies, Fresh coriander','Heat desi ghee in karahi. Add mutton and cook on high heat until brown. Add ginger-garlic paste. Add tomatoes and cook until soft. Add salt and half the black pepper. Cover and cook until meat is tender. Add remaining black pepper and green chilies. Garnish with coriander. Serve with naan.',60,750,'namak_mandi_karahi.jpg','Pakistani','non_veg','Medium',45,c_peshawar,false,true,false),
  ('Mutton Korma','Rich aromatic curry from Peshawar with mutton slow-cooked in yogurt, fried onions, and whole spices.','1 kg mutton, 2 cups yogurt, 3 fried onions, 2 tbsp ginger-garlic, 1 cup oil, 2 tbsp red chili powder, 1 tbsp garam masala, 1/2 cup almond paste, 1/2 cup khoya, Saffron','Blend fried onions with yogurt. Heat oil, add ginger-garlic and mutton. Brown the meat. Add onion-yogurt paste and spices. Cook on low heat until oil separates. Add water and simmer until mutton is tender. Add almond paste, khoya, and saffron. Sprinkle garam masala. Serve with naan.',120,680,'peshawari_korma.jpg','Pakistani','non_veg','Medium',38,c_peshawar,false,true,false),
  ('Lamb Sajji','Whole lamb leg marinated with salt and green papaya, slow-roasted over charcoal until smoky and tender.','1 whole lamb leg (3-4 kg), 1/2 cup salt, 1/4 cup green papaya paste, 2 tbsp black pepper, 1/4 cup vinegar, 4 cups basmati rice, Whole spices','Make deep slits in meat. Rub with salt, green papaya, black pepper, and vinegar. Marinate overnight. Skewer and roast over charcoal for 3-4 hours, turning every 30 minutes. Cook rice with spices and stuff inside lamb cavity. Serve with mint chutney.',240,850,'peshawari_sajji.jpg','Pakistani','non_veg','Medium',75,c_peshawar,false,true,false)
  ON CONFLICT DO NOTHING;

  -- Multan
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Sohan Halwa','Legendary sweet treat from Multan made from wheat starch, sugar, ghee, and nuts.','1 cup wheat starch, 2 cups sugar, 2 cups water, 1 cup ghee, 1/2 cup milk, 1/4 cup almonds, 1/4 cup pistachios, 1 tsp cardamom','Heat ghee in pan. Make sugar syrup separately. Add wheat starch to ghee, stirring continuously. Gradually add sugar syrup and milk. Cook until mixture thickens and leaves pan. Add cardamom and nuts. Pour into greased tray. Cool and cut into pieces.',90,380,'sohan_halwa.jpg','Pakistani','veg','Mild',5,c_multan,true,false,false),
  ('Mango Kulfi','Creamy frozen dessert made with fresh Multan mangoes known as the best in Pakistan.','2 cups fresh Multan mango pulp, 1 liter milk, 1/2 cup khoya, 1/2 cup sugar, 1/4 cup milk powder, 1 tbsp cornflour, 1 tsp cardamom, 1/4 cup pistachios','Boil milk and reduce to half. Add khoya, milk powder, and cornflour. Cook until thickened. Add sugar and cardamom. Cool completely. Fold in mango pulp and nuts. Pour into molds and freeze for 8 hours. Unmold and serve.',480,320,'multani_kulfi.jpg','Pakistani','veg','Mild',7,c_multan,true,false,false),
  ('Channa Chaat','Spicy tangy chickpea chaat that''s a street food favorite in Multan.','2 cups boiled chickpeas, 2 boiled potatoes, 1 onion, 2 tomatoes, 1/4 cup tamarind chutney, 2 tbsp mint chutney, 1 tbsp chaat masala, 1 tbsp pomegranate seeds','Mix chickpeas, potatoes, onion, and tomatoes. Add both chutneys and mix well. Sprinkle chaat masala, red chili powder, roasted cumin, and pomegranate seeds. Garnish with coriander and sev. Serve with poori.',15,280,'channa_chaat.jpg','Pakistani','veg','Medium',10,c_multan,true,false,false),
  ('Pati Gali Biryani','Unique biryani from Multan''s famous Pati Gali with distinctive yellow color and local spices.','1 kg chicken, 4 cups basmati rice, 1 cup yogurt, 2 tbsp ginger-garlic, 2 tbsp yellow biryani masala, 1/2 cup milk with saffron, 2 tbsp kewra water, 1 cup fried onions','Marinate chicken with yogurt, ginger-garlic, half biryani masala. Cook rice until 70% done. Layer chicken and rice in pot. Sprinkle remaining biryani masala, fried onions, saffron milk, and kewra water. Cook on low heat for 20 minutes. Serve with raita.',75,620,'pati_gali_biryani.jpg','Pakistani','non_veg','Medium',34,c_multan,false,true,false),
  ('Sajji','Multan''s version of Balochi classic with locally grown rice and unique spice blend.','1 whole baby lamb (5-6 kg), 1/2 cup salt, 1/4 cup Multani spice blend, 4 cups basmati rice, 1 cup oil, 2 onions, 2 tomatoes','Marinate lamb with salt and spice blend overnight. Prepare rice with onions, tomatoes, and whole spices until 70% done. Stuff rice into lamb''s cavity and sew closed. Roast in tandoor for 4-5 hours. Serve with mint chutney.',360,900,'multani_sajji.jpg','Pakistani','non_veg','Medium',70,c_multan,false,true,false)
  ON CONFLICT DO NOTHING;

  -- Quetta
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Sajji','Whole lamb marinated with salt and green papaya, slow-roasted over open fire until tender and smoky.','1 whole lamb leg (3-4 kg), 3 tbsp salt, 2 tbsp green papaya paste, 1 tbsp black pepper, 2 tbsp vinegar, 2 cups basmati rice','Make deep slits in meat. Rub with salt, green papaya, black pepper, and vinegar. Refrigerate overnight. Skewer and roast over charcoal for 2-3 hours, turning every 30 minutes. Serve with mint chutney and lemon wedges.',180,950,'quetta_sajji.jpg','Pakistani','non_veg','Medium',85,c_quetta,false,true,false),
  ('Landhi','Traditional Balochi preserved meat where mutton is dried in sun and wind during winter.','2 kg mutton, 1/2 cup salt, 2 tbsp black pepper, 2 tbsp cumin crushed, 2 tbsp coriander crushed, 1 tbsp red chili flakes','Cut mutton into long thin strips. Mix spices and rub generously on meat. Hang strips in cool, dry, well-ventilated area for 20-30 days during winter. Meat becomes hard and dry. To cook, wash dried meat, boil until tender, cook with rice.',28800,420,'landhi.jpg','Pakistani','non_veg','Medium',35,c_quetta,false,true,true)
  ON CONFLICT DO NOTHING;

  -- Faisalabad
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Channay','Fiery tangy chickpea curry that defines breakfast culture in Faisalabad.','2 cups chickpeas, 2 onions, 2 tomatoes, 2 tbsp ginger-garlic, 4 green chilies, 1/4 cup oil, 2 tbsp dried mango powder, 1 tbsp pomegranate seeds','Pressure cook chickpeas until soft. Heat oil, add cumin and onions. Fry until golden. Add ginger-garlic and tomato puree. Cook until oil separates. Add spices and chickpeas. Simmer for 20 minutes. Add dried mango powder and garam masala. Serve with poori.',60,520,'faisalabadi_channay.jpg','Pakistani','veg','Hot',18,c_faisalabad,true,true,false)
  ON CONFLICT DO NOTHING;

  -- Rawalpindi
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Murgh Cholay','Tender chicken with spicy chickpeas in rich tangy gravy - Rawalpindi style.','500g chicken, 2 cups chickpeas, 1 cup yogurt, 2 tbsp ginger-garlic, 2 tbsp Kashmiri red chili, 2 tbsp dried mango powder, 4 boiled eggs, 1/2 cup oil','Pressure cook chickpeas. Marinate chicken with yogurt and spices. Cook chicken until tender and shred. Prepare chickpea gravy with onions, tomatoes, and spices. Add shredded chicken and simmer. Add boiled eggs. Serve with naan.',60,620,'murgh_cholay.jpg','Pakistani','non_veg','Hot',42,c_rawalpindi,false,true,false),
  ('Channay','Legendary black chickpea dish from Rawalpindi''s Kartarpura area.','2 cups black chickpeas, 2 onions, 2 tbsp ginger-garlic, 2 tomatoes, 1 tbsp dried ginger powder, 1 tsp asafoetida, 2 tbsp red chili powder','Soak black chickpeas overnight. Pressure cook until soft. Heat oil, add onion puree. Cook until golden. Add ginger-garlic, tomato puree, and spices. Cook until oil separates. Add chickpeas and simmer for 20 minutes. Serve with puri.',480,380,'kartarpura_channay.jpg','Pakistani','veg','Medium',15,c_rawalpindi,true,true,false)
  ON CONFLICT DO NOTHING;

  -- Sialkot
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Kulfi Falooda','Sialkot''s famous layered dessert with creamy kulfi and falooda.','1 liter milk, 1/2 cup khoya, 1/2 cup sugar, 1/4 cup milk powder, 1 tbsp cornflour, 1 tsp cardamom, 1/2 cup falooda sev, 2 tbsp basil seeds, 1/2 cup rose syrup','Boil milk and reduce to half. Add khoya, milk powder, and cornflour. Cook until thickened. Add sugar and cardamom. Freeze in molds. Cook falooda sev and soak basil seeds. Layer rose syrup, basil seeds, falooda, and kulfi. Garnish with nuts.',480,450,'sialkot_kulfi_falooda.jpg','Pakistani','veg','Mild',8,c_sialkot,true,false,false),
  ('Gola Ganda Kala Khatta','Sialkot''s signature shaved ice dessert with black plum syrup.','Ice block, 1 cup Kala Khatta syrup, 1/2 cup sugar, 1/2 cup water, 1 tsp black salt, 1 tsp chaat masala','Boil black plums with water, sugar, and black salt. Reduce and strain. Shave ice and pack into cup. Pour Kala Khatta syrup. Sprinkle chaat masala. Serve immediately.',15,180,'gola_ganda.jpg','Pakistani','veg','Mild',0,c_sialkot,true,false,true),
  ('Chicken Pulao','Fragrant rice dish with tender chicken and aromatic whole spices.','1 kg chicken, 4 cups basmati rice, 2 onions, 2 tbsp ginger-garlic, 1 cup yogurt, 2 tbsp red chili powder, 1/2 cup oil, Whole spices','Heat oil and fry onions until golden. Add chicken and ginger-garlic. Cook until brown. Add yogurt and spices. Add water and whole spices. When water boils, add soaked rice. Cook on high until water absorbs, then cover and cook on low for 15 minutes.',60,580,'sialkot_pulao.jpg','Pakistani','non_veg','Medium',35,c_sialkot,false,true,false),
  ('Samosa Chaat','Delicious chaat with crushed samosas, chickpeas, yogurt, and chutneys.','6 samosas, 1 cup chickpeas, 1 cup yogurt, 1/2 cup tamarind chutney, 1/2 cup mint chutney, 1/4 cup chaat masala, 1 onion, Sev','Crush samosas into bite-sized pieces. Add boiled chickpeas. Pour beaten yogurt. Add both chutneys. Sprinkle chaat masala. Add chopped onion. Mix gently. Garnish with coriander and sev. Serve immediately.',15,350,'samosa_chaat.jpg','Pakistani','veg','Medium',8,c_sialkot,true,false,false)
  ON CONFLICT DO NOTHING;

  -- Hyderabad
  INSERT INTO recipes_recipe (title,description,ingredients,instructions,prep_time,calories,image,cuisine,dietary_type,spice_level,estimated_protein,city_id,is_vegetarian,is_sugar_free,is_low_fat)
  VALUES
  ('Bhugga','Flavorful Sindhi dish of goat meat and spinach slow-cooked with traditional spices.','500g goat meat, 2 cups spinach pureed, 2 onions, 2 tomatoes, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 1 tbsp garam masala, 1/2 cup oil','Heat oil and fry onions until golden. Add ginger-garlic and meat. Cook until meat browns. Add tomato puree and spices. Cook until oil separates. Add spinach puree and water. Cook on low heat until meat is tender. Add garam masala. Serve with rice.',90,540,'hyderabadi_bhugga.jpg','Pakistani','non_veg','Medium',35,c_hyderabad,false,true,false),
  ('Sindhi Kadi Chawal','Tangy gram flour curry with vegetables served over steamed rice.','1 cup gram flour, 2 cups yogurt, 6 cups water, 2 onions, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 1 tsp turmeric, Vegetables','Mix gram flour with yogurt and water. Heat oil, fry onions until golden. Add ginger-garlic and vegetables. Add gram flour mixture and spices. Simmer for 45 minutes. Prepare tadka with ghee, cumin, mustard seeds. Pour over kadi. Serve with rice.',75,420,'sindhi_kadi.jpg','Pakistani','veg','Mild',12,c_hyderabad,true,true,false),
  ('Pappu Masala','Spicy lentil dish with toor dal, garlic, tomatoes, and generous ghee.','2 cups toor dal, 1 onion, 2 tomatoes, 2 tbsp ginger-garlic, 2 tbsp red chili powder, 1/2 cup ghee, 1 lemon','Pressure cook dal with turmeric until soft. Heat ghee, add onion. Fry until golden. Add ginger-garlic and tomatoes. Add spices. Add cooked dal and simmer for 10 minutes. Add lemon juice. Serve with rice or roti.',40,380,'pappu_masala.jpg','Pakistani','veg','Medium',18,c_hyderabad,true,true,false),
  ('Double Roti','Hyderabad''s unique pressed sandwich with spicy potato filling and chutneys.','4 potatoes, 1 onion, 2 green chilies, chaat masala, Mint chutney, Tamarind chutney, Garlic chutney, White bread, Butter','Mix mashed potatoes with spices. Toast bread slices with butter until golden. Spread chutneys on bread. Place potato filling on one slice. Top with onion and tomato. Cover with second slice. Press and toast until crispy. Serve hot.',25,350,'double_roti.jpg','Pakistani','veg','Medium',8,c_hyderabad,true,false,false)
  ON CONFLICT DO NOTHING;
END $$;