# Generated by Django 5.0.6 on 2026-06-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_condition', models.CharField(choices=[('diabetes', 'Diabetes'), ('blood_pressure', 'Blood Pressure'), ('heart_condition', 'Heart Condition'), ('balanced', 'Balanced')], default='balanced', max_length=50)),
                ('dietary_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=50)),
                ('weekly_plan', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
